site_name: Test website for IAPR TC11
repo_url: https://github.com/TC101-demo/TC101-demo.github.io
site_description: Test website.
site_author: IAPR TC11 officers
theme:
    name: material
    logo: img/200px-Tc-11_Logo_v2_72dpi.png
    # collapse_navigation: true
    custom_dir: theme_customizations
edit_uri: edit/main/docs/
nav:
  - index.md
  - Newsletters:
    - newsletters/2021-04.md
  - Datasets:
    - datasets/sample_dataset.md
    - datasets/NewDummyDataset.md
  - More information:
    - contact.md
    - 'Twitter TC10': 'https://twitter.com/IAPR_TC10'
    - 'Twitter TC11': 'https://twitter.com/IAPR_TC11'
plugins:
  - search
  - macros
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
  - attr_list
  - fontawesome_markdown
extra:
    datasets: _datasets/
strict: true
# new analytics
# google_analytics: ['G-????????', '????DOMAIN????']
